import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
const inter = Inter({ subsets: ['latin'] })
import { SliderData } from '../components/SliderData'
import Instagram from '../components/Instagram'
export default function Home() {
  return (
    <>
      <Head>
        <title>Photography portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero title="Captur Photography" message="I love taking photos of nature. I capture moments in nature and keep them alive."/>
      <Slider Slides={SliderData}/>
      <Instagram />

    </>
  )
}
